name: prod-ec2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: 
     -self-hosted
     -prod

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up NVM
        run: |
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          nvm use 20

      - name: Install dependencies
        run: |
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          npm ci

      - name: Build project
        run: |
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          npm run build

      - name: Restart app with PM2
        run: |
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          pm2 reload aeo-server || pm2 start dist/index.js --name aeo-server
